import Head from "next/head";
import Layout from "../../components/layout";

export default function Service() {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <h1>서비스입니다.</h1>
        </Layout>
    )
}